---
title: 'Contribución de los RPAS en investigación y conservación en espacios protegidos:
  presente y futuro'
author:
- affiliation: Trabajo Fin de Curso de Experto Universitario en Vehículos Aéreos no
    Tripulados y sus Aplicaciones Civiles. Edición 2016 - 2017. Universidad de Cádiz.
    12/05/2017
  name: 'Autor: Jesús Jiménez López'
- name: 'Supervisora: Margarita Mulero-Pázmány'
bibliography:
- ~/Documents/CURSOS/drones/RTF/project/internet.bib
- ~/Documents/CURSOS/drones/RTF/project/master.bib
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    pandoc_args:
    - -V
    - classoption=onecolumn
    template: ~/Documents/CURSOS/drones/RTF/project/svm.latex.ms.tex
    toc: yes
  html_document: default
  word_document:
    toc: yes
geometry: margin=1in
keywords: RPAs, UAVs, drones, espacios naturales, conservación, biodiversidad, investigación,
  innovación
fontfamily: mathpazo
spacing: double
abstract: En este estudio se describe el estado actual y las tendencias en el uso
  de los RPAS en proyectos científicos con fines de conservación en espacios naturales
  protegidos, mediante la recopilación y revisión de material bibliográfico en forma
  de artículos científicos, revistas, proyectos de conservación y otras fuentes de
  información relevantes.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introducción

Las aplicaciones civiles de las aeronaves pilotadas remotamente (siglas en inglés RPAS, también conocidos como sistemas aéreos no tripulados, UAS, drones) han sido planteadas en un número cada vez mayor de artículos científicos. Durante los últimos años se ha producido un incremento significativo de las líneas de investigación sobre  vida silvestre en espacios protegidos que hacen uso de RPAS [@Linchant2015; @Christie2016]. En la mayoría de los casos son estudios pilotos que evalúan la capacidad de estos sistemas frente a instrumentos tradicionales de apoyo a la conservación, delimitando sus ventajas e inconvenientes, estableciendo pautas y recomendaciones de uso y abriendo nuevas perspetivas de aplicación.

  A inicios de 1980 comenzaron a realizarse los primeros experimentos con RPAS en temas ambientales  con el objetivo de adquirir fotografías aéreas y demostrar su utilidad en aplicaciones forestales, la gestión de recursos pesqueros o el acoplamiento de sensores para estudios atmosféricos [@Tomlins1983]. Para finales del siglo XX aparecen los primeros estudios de vegetación en especies amenazadas [@quilter1997vegetation], mientras que con la llegada del nuevo milenio el número de  publicaciones comienza a aumentar significativamente [@Hardin2013]. En la actualidad existen algunas iniciativas que tratan de recoger el estado actual de los RPAS en las áreas de la ecología y conservación. Recientemente, la revista *Remote Sensing in Ecology and Conservation* hizo una llamada a la comunidad científica para el envío de propuestas, con objeto de sensibilizar a estudiantes y profesionales y demostrar el uso responsable de RPAS. Es de esperar que del resultado de este llamamiento se produzca un aumento significativo de la literatura científica en este ámbito. Por otro lado, es remarcable la mayor presencia de portales en internet que centran su actividad en torno a las aplicaciones con RPAS. En el campo de la investigación aplicada a la  conservación, el portal web  <http://conservationdrones.org/>  es un referente mundial, cuyos contenidos ilustran proyectos recientes de carácter pionero, por lo que no siempre aparecen reflejados en la literatura científica. La popularidad de los RPAS ha traspasado el ámbito científico-técnico, dando lugar a la aparición de comunidades de usuarios con amplia presencia en internet.  Uno de los portales más activo es <http://diydrones.com/>, que  reune a aficionados  afines a la filosofía "hazlo tú mismo" (*do it yourself*) que fomenta el uso de plataformas abiertas frente a los tradicionales sistemas cerrados ofertados por la industria tradicional del sector. Esto ha dado como resultado la reducción de los costes de estos equipos y junto con el desarrollo de software libre especializado,  han permitido democratizar la tecnología, acercándola a un mayor número de usuarios y organizaciones. La comunidad científica se ha visto probablemente beneficiado de esta tendencia general, puesto que la flexibilidad en el ensamblaje de RPAS ofrece en principio un mayor grado de personalización, permitiendo incluir diferentes sensores y sistemas de control según las necesidades concretas de cada proyecto y dentro del propio grupo de investigación [@Koh2012]. En el terreno comercial, cada vez son más las empresas que ofrecen RPAS de grandes prestaciones y cualificados para desarrollar aplicaciones profesionales, estimulando la competencia en el sector.

Las limitaciones desde el punto de vista financiero y tecnológico de la teledetección, por la cual se obtienen imágenes de la superficie terrestre a partir de sensores instalados en plataformas aéreas o espaciales,  son descritas por diversos autores [@Koh2012; @Rodriguez2012]. Si bien es posible adquirir imágenes satelitales a bajo coste o prácticamente nulo (LandSat, MODIS, Sentinel, etc.), la mayor parte de estas plataformas operan a escala global o regional. La limitada resolución espacial y temporal, junto con los problemas de presencia de nubes especialmente acusados en zonas tropicales, reduce la viabilidad de la teledetección en la recolección de datos a escala suficientemente detallada para hacer frente a los requerimientos de estudios ecológicos a nivel de especies, hábitats o poblaciones [@Wulder2004]. Además, el gran tamaño de estas áreas protegidas reducen en muchos casos la efectividad y aumenta significativamente los costes de los trabajos de campo, mientras que aumenta los riesgos en zonas especialmente inaccesibles. Como consecuencia,  los RPAS se han posicionado como un complemento adecuado para las actividades de conservación [@Zahawi2015], a pesar de la reducida autonomía de vuelo que reduce la capacidad de estos sistemas para sobrevolar regiones extensas. En países en vías de desarrollo, especialmente sensibles en cuanto a dotaciones presupuestarias y capacidades técnicas, se están desarrollando con éxito programas de monitoreo y vigilancia a partir del uso de RPAS, eliminando alguno de los inconvenientes descritos con anterioridad. Por ejemplo, mediante la captura de imágenes aéreas en el delta del Volta, Ghana, un equipo de científicos mide los efectos del cambio climático  en zonas costera y evalua la efectividad de las medidas de prevención y restauración frente a los procesos erosivos [@Georg2016]. Los vehículos aéreos tripulados ofrecen en principio una mejor alternativa en la captura de imágenes de la superficie terrestre, sin embargo su uso no está justificado en estudios a escala local, debido a costes operacionales excesivamente altos. Por otro lado,  el riesgo de sufrir accidentes aéreos es mayor, situándose como primera causa de mortandad en especialistas en vida silvestre en los Estados Unidos [@Sasse2003]. 

Con objeto de reducir el impacto de los drones en estudios de fauna, algunos experimentos analizan la respuesta de aves frente a RPAS [@Vas2015]. Otros ensayos se centran en mamíferos y miden el estreś fisiológico y posibles cambios en el comportamiento frente a vuelos realizados con RPAS [@Ditmer2015]. Fruto de los resultados obtenidos, se están comenzando a documentar manuales de buenas prácticas y recomendaciones con objeto de reducir el impacto negativo en el bienestar y evitar perturbaciones en los patrones de comportamiento de las especies.

Finalmente, algunos autores señalan la necesidad de mejorar el marco regulatorio respecto al uso civil de los RPAS [@Nugraha2016]. En los Estados Unidos y en la mayoría de los países de Europa consultados, se han adoptado leyes provisionales que en cierta medida equiparan el manejo de los RPAS con el de aeronaves tradicionales. Este tipo de restricciones podría limitar las posibilidades de uso de los RPAS en el ámbito de la conservación, por lo que se hace patente la necesidad urgente de armonizar la legislación en relación a este tipo de actividades. En términos generales, la situación en América Latina es desigual, con algunos países que siguen sin desarrollar leyes específicas para hacer frente al auge de los RPAS tanto en el sector civil como militar [@Nacion2013]. África es uno de los continentes donde el impacto de los drones en conservación ha tenido mayor repercusión. Sin embargo, según la opinión de algunos conservacionistas, su uso no ha estado exento de problemas, dando como resultado gobiernos que han prohibido total o parcialmente la operación con drones, argumentando problemas de seguridad nacional en detrimento de la protección de los espacios naturales protegidos [@Andrews2014]. La incertidumbre de los usuarios ha promovido el  desarrollo de asociaciones con objeto de asesorar sobre los aspectos legales a tener en cuenta durante la operación. En España, la Asociación Española de Drones y Afines <https://www.aedron.com> promueve un uso consciente y responsable de los RPAS y organiza seminarios para informar a los socios sobre temas de interés. En su web se puede consultar el borrador de la nueva normativa que regula la utilización civil de las aeronaves pilotadas por control remoto en España [@Aedron2017]. A nivel global han surgido otras iniciativas, siendo la Asociación Internacional para Sistemas de Vehículos No Tripulados (AUVSI) <http://www.auvsi.org>  la organización sin fines de lucro más grande del mundo dedicada al avance de la comunidad de usuarios de sistemas aéreos no tripulados.

## Los espacios naturales protegidos

Los espacios naturales protegidos son aquellos en los que la intervención del hombre no ha llegado a alterar de forma significativa la presencia y funcionamiento de los elementos bióticos y abióticos que lo integran [@Bravo2008]. Cumplen con finalidades de protección y conservación del medio biofísico y cultural, donde se promueven iniciativas en el ámbito científico, educativo y de restauración, actividades recreativas y turísticas compatibles con el medio natural  y acciones de índole socioeconómica enmarcadas en el desarrollo sostenible del territorio. Están amparados bajo alguna figura nacional o internacional de protección y regulados a través de los planes de manejo específicos. A pesar de que el número de áreas protegidas ha experimentado un aumento considerable a nivel mundial, con un 15.4 % de la superficie terrestre y un 8.4% de las áreas marinas bajo alguna figura de protección [@juffe2014protected] , hay autores que resaltan la necesidad de mejorar las herramientas de gestión de áreas protegidas que aseguren la efectividad de la conservación de la biodiversidad [@Chape2005]. Por otra parte  algunas áreas protegidas sufren procesos de degradación, continúan disminuyendo en tamaño o han dejado de existir [@Mascia2011], o bien han sido declaradas bajo criterios oportunistas que no reflejan necesariamente el valor ecológico de los ecosistemas a preservar [@Knight2007]. En un reciente informe realizado por la Sociedad Zoológica de Londres [@Living2016] , se calcula que el tamaño de las poblaciones de vida silvestre ha disminuido en un 52 % en el periodo de 1970 hasta 2012. Todos los indicios apuntan al hombre como principal desencadenante de la ya denominada sexta extinción masiva en nuestro planeta [@Barnosky2011], hasta el punto de que algunos investigadores comienzan a hablar del antropoceno, como inicio de una nueva época del Cuaternario. La fragmentación del hábitat, el aumento de la contaminación, especialmente grave en ecosistemas de agua dulce, la sobreexplotación de los recursos, las consecuencias a nivel global del cambio climático y el impacto de las especies invasoras sobre poblaciones autóctonas han sido identificados como las principales amenazas para la diversidad biológica [@Conabio2017]. 

El Grupo sobre Observaciones de la Tierra (GEOBON) ha identificado un conjunto de variables esenciales para la biodiversidad [@Pereira2013] con objeto de desarrollar un abanico de indicadores que permitan conocer el estado global de nuestros ecosistemas y ayuden a la mejor toma de decisiones en materia de biodiversidad  mediante  la integración  de técnicas de observación remota  y observaciones in-situ como piezas clave para el levantamiento de información ambiental [@Forum2008]. Por otra parte,  el Convenio sobre la Diversidad Biológica desarrollado como parte del  Programa de las Naciones Unidas para el Medio Ambiente (PNUMA)  estableció en Nagoya (Japón) un plan estratégico para el periodo 2011-2020 que incluye las denominadas *metas de Aichi* para la diversidad biológica. Dentro de los objetivos planteados destaca el aumento de los sistemas de áreas protegidas de especial importancia para la biodiversidad y los servicios ecosistémicos (Meta 11)  y se establece una serie de criterios de gobernanza, equidad, gestión, representatividad y conectividad ecológica para la inclusión de áreas prioritarias para la conservación. Para hacer frente a la crisis ambiental actual, es necesario desarrollar soluciones que mejoren  el estado de la biodiversidad. 

En este contexto, el presente documento realiza una revisión de los RPAS  en estudios de conservación y gestión de áreas protegidas, mencionando las barreras técnicas y legales que limitan su efectividad.


# Métodos

Para alcanzar los objetivos propuestos se procedió a la revisión bibliográfica de artículos, literatura gris, tesis de postgrado, sitios web y revistas especializadas, siguiendo una línea similar a otros estudios realizados con anterioridad [@Linchant2015; @Christie2016] Mediante artículos seleccionados para el curso de Experto Universitario en Vehículos Aéreos no Tripulados y sus Aplicaciones Civiles organizado por la Universidad de Cádiz en su edición de 2016-2017, junto con herramientas como Google Schoolar, ResearchGate y Mendeley Desktop, se obtuvo la mayor parte de la bibliografía seleccionada, mientras que el uso de los motores de búsqueda por internet incluyeron el resto de materiales mencionados. Los principales criterios de búsqueda por palabras claves incluyeron los vehículos aéreos no tripulados en sus diversas acepciones y acrónimos (RPAS, UAV, drones, etc.),  junto con una variedad de términos que hacen referencia a áreas naturales protegidas, fundamentalmente en inglés. Dicha actividad tuvo lugar desde el 4 de Abril de 2017 hasta el 12 de Mayo del mismo año. 

La información obtenida se categorizó según el propósito de aplicación de los RPAS en relación directa o indirecta con la conservación en espacios protegidos. La mayoría de las fuentes analizadas se centran en proyectos de conservación a escala local  y estudios de viabilidad de los RPAS en la caracterización de poblaciones y comunidades de vida silvestre, especialmente en estudios de distribución y abundancia. La literatura comienza a ser igualmente prolífica en actividades de monitoreo y mapeo en ecosistemas terrestres y acuáticos, nicho actualmente ocupado por las plataformas aéreas y espaciales de teledetección ambiental. A pesar de la dificultad de encontrar artículos dedicados al uso de RPAS en el control y vigilancia de áreas protegidas, es uno de los temas que mayor debate social genera y no es extraño encontrar iniciativas gubernamentales o promovidas por organizaciones ambientales en la lucha contra la caza y pesca furtiva.  Adicionalmente se revisan algunos aspectos de calado social recogidos en los materiales seleccionados y que son motivo de controversia, con especial referencia a la privacidad de las personas y el bienestar de las especies estudiadas, las implicaciones éticas y legales y la repercusión en la efectividad de los RPAS en la conservación a largo plazo. En cualquier caso, dado el carácter multidisciplinar y multipropósito de estos estudios existe cierto solape entre los objetivos marcados dentro de cada proyecto,  por lo que se ha tenido en cuenta aquellos objetivos que mayor peso tienen en el contexto de la investigación. 

La información seleccionada se presenta en formato tabular, identificando los países implicados,  el propósito principal de cada estudio, las técnicas y sistemas empleados, haciendo referencia explicita al tipo de aplicación y plataformas de vuelo, tanto de ala fija como de pala rotatoria. Finalmente se discuten los posibles escenarios  que presentan  los RPAS como herramientas fundamentales para contribuir a la consecución de los planes de conservación en espacios protegidos, destacando algunas tendencias y oportunidades que aparentemente aún no han sido convenientemente explotadas.


<!-- \newgeometry{margin=1cm} -->
\begin{landscape}
\begin{table}

\caption{APLICACIONES RPAS EN ESPACIOS NATURALES PROTEGIDOS}
\tiny
\begin{tabular}{p{3cm}p{1.2cm}p{3cm}p{1cm}p{2cm}p{2cm}p{1cm}p{2cm}p{2cm}p{1cm}p{2cm}}

\cmidrule(r){1-11}

Estudio & Área protegida & Objetivo/s & País & Lugar & Especie & Tipo RPAS & Modelo RPAS & Sensor & Georref. & Costo \\ \cmidrule(r){1-11}

\multicolumn{11}{c}{} \\
\multicolumn{11}{c}{ {\bf ESTUDIOS DE FAUNA Y VIDA SILVESTRE}  } \\
\multicolumn{11}{c}{} \\

\cite{PazmanyMulero2015}  & Si & Estudio comparativo modelos distribución de especies & España & Parque Nacional de Doñana & Bos taurus  & Ala fija & Easy Fly plane, Ikarus autopilot, Eagletree GPS logger & Panasonic Lumix LX-3 11MP & Si & 
5700 euros \\ 

\citealt{Hodgson2013} & Si & Detección e identificación de dugongs.  Comprobar actitud  RPAS en diferentes condiciones ambientales. Determinar altura y resolución ideal  & Australia & Shark Bay Marine Park & Dugong & Ala fija &  ScanEagle & Nikon D90 12 megapixel digital SLR camera  & Si & ?  \\ 

\cite{Longmore2017} & No & Desarrollo de software detección especies infrarrojo térmico & Inglaterra & ? & Fauna & Multicóptero & 750mm carbon-folding Y6 multi-rotor APM 2 autopilot 3Drobotics & FLIR, Tau 2 LWIR Thermal Imaging Camera Core  & ? & ?  \\ 

\cite{Wilson2017}  & No & Monitoreo bioacústico con RPAS & USA & State Game Lands & Aves  & Multicóptero & DJI Phantom 2 & ZOOM H1 Handy Recorder  & Si & ? \\ 

\cite{Bayram2016}  &  No & Detección de collares VHF & ? & ? & Oso (Ursus)  & Multicóptero & DJI F550 hexarotor, Pixhawk autopilot & Telonics MOD-500 VHF, Uniden handheld scanner  & Si & ? \\ 

\cite{Christie2016}  &  Si  & Estimación abundancia & USA &  Aleutian Islands & León marino de Steller (Eumetopias jubatus) & Multicóptero & APH- 22 hexacopter & ?  & Si & \$ 25.000 , \$ 3000 alquiler barco, or \$ 1700 por sitio \\ 

\cite{Christie2016}  &  Si & Estimación abundancia & USA &  Monte Vista National Wildlife Refuge & Grus canadensis (sandhill cranes)  & Ala fija & Raven RQ- 11A & ?  & Si & \$ 400 \\ 

\multicolumn{11}{c}{} \\
\multicolumn{11}{c}{{\bf  MONITOREO DE ECOSISTEMAS TERRESTRES Y ACUÁTICOS  }} \\
\multicolumn{11}{c}{} \\

\cite{Perroy2017}  & No & Monitoreo de plantas invasoras & USA & Pahoa, Hawai & Miconia calvescens & Multicóptero & DJ Inspire-1 & DJI FC350 camera  & Si & ?  \\ 

\cite{Szantoi2017}  & Si & Mapeo de hábitat & Indonesia & Gunung Leuser National Park & Orangután (Pongo abelii)  & Ala fija & Skywalker & Canon S100  & Si & \$ 4000 \\ 
  
\cite{Ivosevic2015}  & Si & Monitoreo hábitats zonas restringidas; Modelos; Comprobar actitud  RPAS en diferentes condiciones ambientales & South Korea & Chiaksan National Park;Taeanhaean National Park &  ? & Multicóptero & DJI Phantom 2 Vision+  & full HD videos 1080p/30fps and 720p/60fps, cámara 14 megapixels 4384x3288 & Si & ? \\ 
  
\cite{Lisein2015}  & No & Discriminación de especies de  hoja caduca, inventario forestal & Bélgica & Grand-Leez & English oak, birches (Betula pendula Roth. and Betula pubescens Ehrh.), sycamore maple (Acer pseudoplatanus L.), common ash (Fraxinus excelsior L.) and poplars (Populus spp.) & Ala fija & Gatewing X100  & Ricoh GR2 GR3 GR4 10 megapixels CCD  & Si & ?  \\ 
  
\cite{Puttock2015}  & Si & Caracterización ecosistemas afectados por la actividad del castor & UK & Devon Beaver Project site & Eurasian beaver (Castor fiber) & Multicóptero & 3D Robotics Y6 & Canon ELPH 520 HS  & Si & ?  \\ 
  
\cite{Zahawi2015}  & No & Caracterización estructura bosques tropicales para acciones de restauración & Costa Rica & Devon Beaver Project site & Varias especies & Multicóptero & 3D Robotics Y6 & Canon S100  & Si & \$ 1500 \\ 
  
\cite{Bustamante2015}  & Si &  Monitoreo de bosques & Brasil & Riverine Forests (Permanent Protected Areas), Rio de Janeiro, Barrãcao do Mendes, Santa Cruz and São Lorenço & Bosques de rivera & Multicóptero & DJI Phantom Vision 2S   & RGB digital camera with 14 mega pixels & Si & \$ 9700  \\ 
  
\cite{Gini2012}  & Si & Modelamiento 3D, clasificación de especies arbóreas & Italy & Parco Adda Nord &  Varias especies &  Multicóptero  &  Microdrones TM MD4-200 & RGB CCD 12 megapixels Pentax Optio A40, modified NIR Sigma DP1 with a Foveon X3 sensor  & Si & ?  \\

\cite{Miyamoto2004}& Si & Clasificación de especies en humedales & Japón & Humedales de Kushiro &  Varias especies & Globo helio  & ? & NIKON F-801, NIKKOR 28 mm f/2.8  & Si & Helio \$ 600, globo \$ 1000  \\ 

\multicolumn{11}{c}{} \\
\multicolumn{11}{c}{{\bf EVALUACIÓN DE INFRAESTRUCTURAS Y RIESGO, VIGILANCIA, ECOTURISMO, IMPACTO EN LA FAUNA }} \\
\multicolumn{11}{c}{} \\

\cite{Lobermeier2015} & No  & Mitigar el riesgo de colisión mediante la instalación de marcadores en líneas electríca & USA & ?  & Aves  & Multicóptero  & Mikrokopter Hexa XL  & KX 171 Microcam & ? & ? \\ 

\cite{Mulero-Pazmany2014a} & Si  & Evaluación riesgo riesgo eléctrico de nidos en postes de alta tensión & España & Parque Nacional de Doñana &  Aves  & Ala fija  & Easy fly St-330 & GoPro Hero 2 11 MP, Panasonic LX3 11MP & Si & 7800 euros  \\ 

\cite{Mulero-Pazmany2014}  & Si  & Vigilancia en áreas protegidas & Africa & KwaZulu-Nata & black rhinoceros (Diceros bicornis), white rhinoceros (Ceratotherium simum)  & Ala fija  & Easy Fly St-330 & Panasonic Lumix LX-3 11 MP, GoPro Hero2, Thermoteknix Micro CAM microbolometer & Si & 13750 euros  \\ 

\cite{Hansen2016} & Si  & Monitoreo actividad visitantes  & Suecia & Kosterhavet National Park &  Humanos  & ?  & ? & ?  & ? & ?  \\ 

\cite{King2014} & Si  & Aplicaciones RPAS en actividades ecoturismo & Suecia & Kosterhavet National Park &  Humanos  & ?  & ? & ?  & ? & ?  \\ 
  
\cite{Vas2015} & Si  & Impacto RPAS  especies aves lacustres  & Francia & e Zoo du Lunaret, Cros Martin Natural Area &  Anas platyrhyncho, Phoenicopterus roseus, Tringa nebularia  & Multicóptero &  Phantom & Hero3 GoPro & Si  & ?  \\ 

\cite{Ditmer2015} & Si  & Impacto  RPAS oso negro americano   & USA & Kosterhavet National Park &  Oso negro americano (Ursus americanus) & Multicóptero & 3DR IRIS Pixhawk & GoPro HERO3+ & ?  & ?  \\ 

\end{tabular}
\end{table}
\end{landscape}

<!-- \restoregeometry -->


# Resultados
  
    
## Estudios de fauna y vida silvestre
  
Uno de los temas centrales de la ecología es el  desarrollo de modelos estadísticos de distribución de especies que  permiten inferir el hábitat potencial o idóneo de  los organismos  a partir de la recolección de información ambiental y datos de presencia procedentes de diversas fuentes [@Mateo2011]. La radiotelemetría es uno  de los métodos más comunes para la recolección de datos de movimiento en individuos marcados con geolocalizadores. Algunos estudios comparan el uso de RPAS frente a estos sistemas [@Mulero-Pazmany2015] en animales de gran tamaño y fácilmente identificables mediante imágenes aéreas de alta resolución, obteniendo resultados similares en cuanto al rendimiento de los modelos pero con diferencias notables en cuanto a costes derivados de la compra de los equipos y gastos de logística, favoreciendo en este caso a los RPAS.  Las limitaciones financieras también afectan al tamaño del muestreo con el uso de geolocalizadores, con el riesgo añadido de marcar individuos bajo criterios no aleatorios, si bien se remarca la ventaja de estos sistemas en cuanto a su capacidad para generar grandes volumenes de datos en un periodo de tiempo mayor. En cuanto a la exactitud posicional, los RPAS tienen un error máximo entre 1 y 3 metros, mientras que los errores del GPS pueden ser mayores a 20 metros. En cualquier caso los autores remarcan que ambas metodologías tienen potencial para complementarse a lo largo de todas las fases del estudio. Otras técnicas innovadoras han sido recientemente ilustradas en artículos cientificos que  evaluan la viabilidad del uso combinado de radiolocalizadores en RPAS en la búsqueda de individuos marcados con radio collares VHF [@Korner2010; @Bayram2016; @Cliff2015; @Leonardo2013]. 

En determinados casos, frente a las dificultades para detectar directamente a la especie de interés, los estudios se enfocan en la localización y caracterización de sus áreas de cría y nidificación [@VanAndel2015]. En áreas protegidas de gran extensión se han ensayado con éxito el conteo de grandes mamíferos terrestres , no habiéndose registrado reacciones adversas en vuelos realizados a una altura mínima de 100 metros [@Vermeulen2013]. La estimación de poblaciones de mamíferos en ecosistemas marinos también ha sido documentada con resultados positivos [@Hodgson2013], mientras que en aves se han usado para estudiar las dinámicas poblacionales en colonias [@Sarda-Palomera2012]. La utilidad de estos sistemas también queda manifiesta en la inspección y caracterización de nidos de aves en zonas de difícil acceso [@Weissensteiner2015], permitiendo evaluar el estado en el que se encuentran de forma menos intrusiva.

Dada la masiva cantidad de información generada, no es de extrañar que se hayan aplicado métodos desarrollados en el campo de la visión computerizada, dirigidos al conteo automático de individuos capturados en las escenas adquiridas por los sensores fotográficos  [@Lhoest2015; @Abd-Elrahman2005a; @VanGemert2015]. Esto conlleva una reducción de los costes respecto al conteo manual de las escenas adquiridas, con la ventaja adicional de no estar sujetos en mayor o menor medida a la interpretación del especialista.  En este sentido, los métodos de observación directa desde vehículos aéreos tripulados también representan desventajas con respecto a la toma de imágenes aéreas, puesto que necesitan un mayor número de observadores que garantizen un conteo exahustivo de las poblaciones para evitar errores en la estimación. 
Fuera de la literatura científica, existen proyectos para el monitoreo de la fauna tanto en ecosistemas marinos como terrestres, en su  mayoría respaldados por organizaciones no gubernamentales y centros de investigación.. A partir de la información recopilada en la comunidad online <https://conservationdrones.org> se han identificado varios estudios relacionados con el registro de individuos en poblaciones de mamíferos marinos, primates y macrofauna en general,  situados en áreas protegidas o frecuentemente visitadas por especies sujetas a alguna figura de amenaza. Por ejemplo, un estudio realizado en la cuenca del Amazonas en Brasil está experimentando el uso de drones para mejorar la estimación de la densidad y abundancia de diferentes especies de delfines, comparándolo con la observación directa realizada por especialistas [@WichS2017]. Dentro de los objetivos de la investigación se contempla la validación y armonización de ambas metodologías y de forma indirecta, evaluar la viabilidad para su aplicación regular en proyectos de monitoreo con similar propósito, teniendo en cuenta el coste-beneficio de la ejecución. 

## Evaluación de infraestructuras y riesgo

Otros trabajos resaltan la utilidad de los RPAS en la evaluación del riesgo de infraestructuras humanas y la puesta en marcha de medidas preventivas frente a especies de aves que nidifican en postes de líneas eléctricas de alta tensión, haciéndolas especialmente vulnerables a colisiones y electrocutamiento. Para la ejecución de trabajos de precisión donde la estabilidad, maniobrabilidad y el detalle en la identificación es esencial  [@Lobermeier2015] se recomienda el uso de multicópteros. En evaluaciones de estructuras lineales de gran extensión en las que el costo y tiempo de vuelo es determinante en contraposición a la resolución espacial, los vehículos de ala fija ofrecen mejores ventajas [@Mulero-Pazmany2014a; @Zhang2016].   

Si bien estos estudios no están dirigidos exclusivamente a áreas protegidas, podrían resultan de especial interés en zonas aledañas de amortiguamiento, donde el desarrollo antrópico puede generar situaciones de conflicto con la fauna  circundante. Por ejemplo, se sabe que hay ciertas especies de aves que nidifican en el suelo, especialmente en zonas de cultivo de cereal. Como actividad previa a la cosecha, realizada generalmente bajo procedimientos mecánicos, se podría realizar un sobrevuelo para identificar posibles nidos, y en su caso, tomar las medidas adecuadas para evitar su destrucción [@Mulero-Negro].

## Monitoreo y mapeo de ecosistemas terrestres y acuáticos 

Durante las últimas décadas el auge de los sensores remotos a bordo de plataformas aéreas o espaciales ha desencadenado un aumento de las aplicaciones para el estudio de los ecosistemas [@Wulder2004]. Los datos obtenidos han permitido desarrollar mapas de cobertura vegetal y suelos, caracterizar hábitats, mejorar la compresión de la estructura y función de las masas forestales, desarrollar modelos digitales de elevaciones o levantar cartas geomorfológicas de aplicación en el modelamiento de distribución de especies. La aparición de los RPAS ha propiciado el análisis cuantitativo de hábitats a un nivel de detalle que no había sido posible anteriormente, bien por motivos económicos o por limitaciones propias de la ingeniería. Este  impulso ha sido especialmente notable con el desarrollo paralelo de sensores multiespectrales e hiperespectrales adaptados a aeronaves de pequeño tamaño, cuyo precio se espera disminuya según las tendencias del sector tecnológico. Dentro de las actividades del Servicio Geológico de los Estados Unidos (USGS) se han realizado vuelos con objeto de clasificar la cobertura vegetal en humedales [@USGS2014]. Otros estudios monitorean la distribución de especies invasoras bajo diferentes condiciones de vuelo y cobertura vegetal [@Perroy2017], mientras que la caracterización  de masas forestales constituye un importante apartado dado el número de artículos que abordan el problema desde diferentes perspectivas. [@Gini2012] emplea un modelo de cuadrocóptero y cámaras en RGB y NIR a baja altura en áreas de pequeña extensión. Debido a la reducida fiabilidad y autonomía de la plataforma y las dificultades para aumentar la capacidad de carga, la planificación del vuelo se ve reducida a tres pasadas con un porcentaje del 80% y 30% de solape longitudinal y transversal respectivamente. [@Lisein2015] realiza un análisis multitemporal de la respuesta espectral frente a variaciones en la fenología en diferentes especies de árboles de hoja caduca y concluye que la variación espectral intraespecífica  es de máximo interés para la optimización de los algoritmos de clasificación y discriminación entre especies. En su investigación,  opera un modelo de RPAS de ala fija, utiliza diferentes sensores en el rango visible e infrarrojo cercano y optimiza los parámetros de vuelo con objeto de cubrir la máxima superficie con el menor número de vuelos posible. [@Zahawi2015] aplica la metodología *Ecosynth*,  un conjunto de herramientas para cartografiar y medir la vegetación en 3D utilizando cámaras digitales y software de visión artificial de código abierto, con objeto de evaluar la eficacia de las acciones de restauración en bosques tropicales mediante RPAS, como alternativa viable para las medidas de campo tradicionales y aplica diferentes modelos predictivos de presencia de pájaros frugívoros a partir de los datos de altura y estructura del dosel vegetal.   

## Vigilancia y apoyo para el cumplimiento de las leyes en áreas protegidas

Los RPAS también tienen especial proyección en el control y vigilancia de áreas protegidas. Así lo demuestran diferentes experiencias enfocadas principalmente en el control de la caza y pesca furtiva. Este tipo de estudios se caracteriza por dar una mayor importancia a la mejora de los sistemas de visión en primera persona (FPV) con objeto de obtener una panorámica en tiempo real de la zona monitoreada, el uso de RPAS de ala fija cuya mayor autonomía frente a los multirrotores permite cubrir una mayor extensión, la necesidad de utilizar cámaras térmicas en condiciones de baja visibilidad, usualmente relacionadas con horas de mayor actividad furtiva,  junto con avances en los sistemas de visión computerizada programados para detectar la presencia de humanos y especies sometidas a la presión de comercio ilegal en áreas protegidas. [@Mulero-Pazmany2014] se enfocan en el rinoceronte africano y constatan las ventajas del video en tiempo real frente a la toma de fotografías, que necesitan un mayor tiempo de postprocesamiento. Adicionalmente recalcan la necesidad de mejorar la resolución de los sensores térmicos para aumentar las posibilidades de detectar actividades sospechosas en horas nocturnas.  [@Duffy2014] analiza las consecuencias de la militarización de las prácticas de conservación, como tendencia cada vez mayor en áreas naturales protegidas de todo el mundo e ilustra el uso de RPAS a través de varios ejemplos. Respecto a zonas costeras, una búsqueda rápida por internet  permite  recoger diversas iniciativas  que tratan de optimizar las labores de control de la pesca ilegal mediante RPAS. Sin embargo no hemos podido constatar estudios científicos que avalen tales iniciativas, por lo que se abre una vía interesante para su investigación. Por ilustrar algunos de los numerosos ejemplos, en Belice se realizó un estudio pionero para el monitoreo de pesquerías mediante un modelo de ala fija Skywalker. El Gobierno de Canarias está considerando el uso de RPAS en labores de control e inspección en zonas de difícil acceso para hacer frente al furtivismo [@Canarias2017]. Finalmente <http://soarocean.org/> es una iniciativa de *National Geographic* y *Lindblad Expedition* para el uso de drones de bajo coste en la protección de los océanos y es un buen punto de partida para buscar aplicaciones pioneras en este ámbito. 


## Ecoturismo

El alto grado de diversificación que ofrece la aplicación de los RPAS en la industria ecoturística queda resumido en un artículo reciente, en el que se exponen posibles actividades recreativas, oportunidades de negocio,  operaciones de búsqueda  y rescate, mapeo y fórmulas para la concesión de operaciones con RPAS en áreas designadas para tal fin [@King2014]. Dentro de la aún escasa literatura, [@Hansen2016] valora la eficacia de los RPAS en el monitoreo de visitantes en áreas marinas y costeras, en combinación con otras soluciones innovadoras.  Según el autor los RPAS permitirían teóricamente operar bajo diferentes condiciones ambientales, mejorando el nivel de detalle y ofreciendo una cobertura continua en el flujo y comportamiento de los visitantes , en contraposición a otras técnicas de uso habitual como la observación manual o la instalación de redes de cámaras de vigilancia. 

## Impacto de los RPAS en la fauna silvestre

La priorización del bienestar del animal debe ser incluida en las aplicaciones de RPAS, estableciendo unos principios éticos que complementen los estándares vigentes en materia de investigación y conservación. [@Vas2015] obtienen resultados prometedores de relevancia en estudios ornitológicos, valorando el impacto del color, la velocidad y el ángulo de vuelo en las respuestas de comportamiento de aves lacustres frente a la aproximación de multirrotores, siendo este último factor el principal desencadenante de cambios en los patrones de comportamiento, especialmente en aproximaciones desde la vertical, a un ángulo de 90º. Finalmente concluyen con una serie de recomendaciones básicas y consideran recomendable extender los ensayos a una amplia gama de RPAS y especies. [@Ditmer2015] mide el estrés fisiológico en el oso negro americano mediante el registro electrónico de la actividad cardíaca en presencia de RPAS. Si bien no registran cambios en los patrones de comportamiento, el aumento de los latidos por minuto (bmp) es significativo en la mayoría de los casos observados. Ante la falta de experiencias que aborden de manera explícita el fenómeno, [@Hodgson2016a] concluyen con una serie de recomendaciones generales como base para un código de buenas prácticas, destacando la adopción del principio de precaución y  respeto a las normas de aviación civil, el entrenamiento específico de los operadores,  la selección apropiada de los equipos, el cese de las operaciones en caso de generar perturbaciones evidentes en las poblaciones estudiadas y el reporte de las observaciones en publicaciones científicas, que permita compartir el conocimiento con vistas a una mejora progresiva en los protocolos de operaciones con RPAS.

# Discusión 

### Estudios de fauna y vida silvestre

A razón de la bibliografía seleccionada, el uso de RPAS de ala fija y multirrotores tienen su ámbito especifico de actuación. En el primer caso, la mayor parte de los estudios se centran en el conteo de poblaciones, con resultados prometedores en la macrofauna.  Todavía es pronto para generalizar su uso en especies de menor tamaño y en zonas de alta cobertura vegetal, si bien el desarrollo de la tecnología LIDAR y sensores de amplio espectro podría ayudar a superar las barreras técnicas. Adicionalmente, es necesario mejorar el conocimiento en cuanto a la planificación de los muestreos realizados con RPAS, para evitar errores en la estimación. Los multirrotores podrían cubrir algunas de las limitaciones anteriormente citadas, pero aún parece no existir estudios que combinen ambos sistemas. Por otro lado, el uso de RPAS puede aumentar la complejidad de la investigación, con equipos de trabajo cada vez más técnicos y necesidades computacionales que no estén al alcance de cualquier institución. En cualquier caso, los RPAS podrían convertirse en una herramienta esencial para especialistas en ecología y su uso podría estar justificado mientras no se registren avances en otras técnicas tradicionales de apoyo a la investigación.

### Evaluación de infraestructuras y riesgo

Los RPAS han demostrado su capacidad para la inspección técnica de recintos industriales. El alto coste que supone la  evaluación de riesgos para la fauna en zonas de alta incidencia de muertes podría persuadir a las autoridades ambientales para fomentar su uso  con fines preventivos. Los RPAs también podrían evitar accidentes mediante la aplicación de medidas disuasorias que eviten la colisión de aves en parques eólicos. Otros usos incluyen la revisión del equipamiento en espacios naturales protegidos, mediante la programación de vuelos periódicos en instalaciones de uso público. Fuera del ámbito de este estudio aunque estrechamente relacionados con la gestión de espacios naturales, los RPAS se posicionan como herramientas fundamentales en la prevención y evaluación de incendios en zonas forestales.

### Monitoreo y mapeo de ecosistemas terrestres y acuáticos 

Los estudios analizados demuestran un gran potencial de los RPAS para integrarse como parte esencial en  estudios relacionados con la teledetección ambiental. El mayor poder de cálculo de los procesadores modernos, así como los recientes avances en fotogrametría han permitido ir superando  las limitaciones tecnológicas para el manejo de grandes volumenes de datos Probablemente sea necesario continuar investigando en el desarrollo de algoritmos cada vez más exactos que mejoren la identificación de las características de interés. 

### Vigilancia y apoyo para el cumplimiento de las leyes en áreas protegidas

El futuro de los RPAS en la lucha contra la caza furtiva y la pesca ilegal en áreas protegidas se enfrentan a limitaciones técnicas que probablemente puedan ser solventadas en los próximos años. Los estudios revisados mencionan la necesidad de desarrollar de sistemas de visión nocturna más eficientes y capaces de discernir actividades de tipo criminal. La autonomía de los RPAS es especialmente crítica en parques naturales de gran extensión, junto con la presencia de condiciones atmosféricas adversas que afectan a la capacidad de vuelo. En algunos paises se prohibe volar más allá del alcance visual del operador, dificultando la posibilidad de realizar inspecciones en tiempo real. Es de esperar que este modo de operar pueda estar sujeto a una regulación especial que favorezca a este tipo de actividades. La mayor parte de los conflictos son de tipo legal y su uso es cuestionable en cuanto a la manera en que podrían infringir la privacidad y las libertades civiles. Todavía es pronto para asegurar si el uso de RPAS en la lucha contra el furtivismo puede persuadir a los infractores, que en muchos casos se enfrentan a situaciones de máxima necesidad. Probablemente el éxito de este tipo de iniciativas requiera de un consenso mayor entre las partes implicadas.

### Ecoturismo

Una permisiva regularización del uso de RPAS en  actividades ecoturísticas en parques naturales podría conducir a situaciones impredecibles. Por un lado la presencia constante del ruido de hélices y motores, la sensación de invasión o falta de privacidad y el impacto visual de los RPAS sobre el paisaje podrían afectar negativamente la experiencia del turista o en su caso, pertubar significativamente los ecosistemas. La sensibilización frente a el abuso de RPAS para la grabación de la vida salvaje  ha resultado en la prohibición de volar con fines recreativos en parques naturales de Estados Unidos y otras partes del mundo. Es necesario mencionar el riesgo real de accidentes  que podrían dan lugar, por ejemplo, a la contaminación de  reservas de agua, debido a la toxicidad de los materiales. El abandono o pérdida de RPAS siniestrados también podría aumentar el riesgo incendios en zonas sensibles, debido a la presencia de componentes inflamables. No parece que se hayan publicado estudios pilotos ni encuestas de opinión que respondan a las cuestiones planteadas y a las implicaciones éticas y legales derivadas de su uso. Aún cuando las posibilidades de ocio son amplias y reconocidas, sería conveniente ser cautelosos frente a la demanda de la industria ecoturística para incorporar los RPAS en sus actividades.


### Impacto de los RPAS en la fauna silvestre

La revisión de la literatura sugiere que aún quedan ciertos nichos que necesitan de mayor atención por parte de la comunidad. Aún no han sido sopesadas convenientemente las implicaciones éticas de los RPAS en estudios de fauna.  Por ejemplo, la mayor parte de los estudios solo abordan marginálmente la presencia o ausencia de reacciones en especies frente a la cercanía de RPAS. Consideramos que los experimentos dirigidos a cuantificar cambios fisiológicos y de comportamiento son insuficientes y que  a pesar del surgimiento de algunas iniciativas y un mayor grado de sensibilización, sería necesario mejorar nuestro conocimiento  actual con objeto de perfeccionar un conjunto de buenas prácticas y recomendaciones dirigidas a especies concretas.  Otros factores claves incluyen la profesionalización de los operadores y la inversión en  modelos de RPAS optimizados para reducir el impacto sobre la fauna y facilitar su observación, especialmente en cuanto a la disminución del ruido de hélices y motores y el diseño de componentes no contaminantes. 


# Conclusiones 

La consolidación de los RPAS como herramientas de gestión e investigación en áreas naturales protegidas están estrechamente ligadas al desarrollo tecnológico de los elementos asociados a la plataforma y el establecimiento de medidas que regulen favorablemente su uso, aumentando las  oportunidades en el sector y estimulando la innovación en áreas de interés para la conservación. Continuamente se producen mejoras en el control de la navegación y autonomía de vuelo, mientras que asistimos a la progresiva minituarización y diversificación de sensores junto  con avances en el campo de la inteligencia artificial. Esta confluencia de factores en rápida expansión  fomenta la aparición de nuevos escenarios con repercusiones éticas y legales. La mayor parte de los gobiernos han reaccionado  estableciendo limitaciones que podrían repercutir negativamente en la capacidad de los RPAS para integrarse en el ámbito civil. Ante esta situación, resulta difícil prever las acciones que cada país va a adoptar a partir de ahora en un intento por armonizar las ventajas e inconvenientes de estos sistemas, por lo que es probable que el futuro de los RPAS en áreas protegidas esté condicionado fundamentalmente por factores políticos y sociales. 


