---
title: 'Contribution of RPAS in research and conservation in protected areas: present
  and future'
author:
- affiliation: University
  name: Jesús Jiménez López
- affiliation: University
  name: Margarita Mulero-Pázmány
bibliography:
- ./internet.bib
- ./master.bib
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    pandoc_args:
    - -V
    - classoption=onecolumn
    template: ./svm.latex.ms.tex
  html_document: default
  word_document: default
csl: taylor-and-francis-chicago-author-date.csl
documentclass: article
keywords: RPAS, UAV, drones, natural protected areas, conservation, biodiversity
numbersections: yes
cls: ./interact.cls
runhead: A Running Head
thanks: null
abstract: Nature conservation has benefited from a wide range
  of technological advances, from remote sensing, camera traps or wildlife tracking
    devices to a continuous development of computational tools and analytical techniques to deal with large amounts of data collected. All of them play an important role in safeguarding biodiversity and better understanding of ecosystem functions. In the last few decades, we have witnessed a growing interest in projects aimed to evaluate the feasibility of RPAS for conservation purposes. So far, RPAS have been tested or directly applied for a variety of research and management activities including environmental and wildlife monitoring or anti-poaching strategies. It remains to be seen how well RPAS complement conservation actions in protected areas, since there are technical, ethical and legal barriers that currently limit their effectiveness. However, through the development of novel solutions and continuous improvement of performance and sensor characteristics, the parallel design of computer intensive statistical methods and a greater concern for animal welfare issues, there are high expectations in the research community and RPAS applications in protected areas is increasingly justified.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

## Current context

Civil applications of remotely piloted aircraft  systems (RPAS, also known as unmanned aerial systems, UAS, drones) have been raised in an growing number of scientific articles. During the last few years there have been a significant amount of  wildlife research projects in natural protected areas using RPAS [@linchant_are_2015; @chabot_wildlife_2015; @christie_unmanned_2016] and it is rapidly taking its place within the broad set of technological solutions that support conservation [@pimm_emerging_2015]. In most cases, feasibility studies were carried out, assessing the capacity of RPAS in relation to traditional conservation instruments by  measuring the overall performance, delimiting their strengths and weakness, and establishing guidelines and recommendations, resulting in new perspectives of application.

Although the potential of RPAS for mapping is tackled at the end of the seventies [@colomina_unmanned_2014], we found some references dating back to the early 1980s, where first trials with RPAS applied on environmental issues began with the objective of acquiring aerial photographs and demonstrating their usefulness in forestry applications, fish resource management or the coupling of sensors for atmospheric studies [@tomlins_remotely_1983]. At the beginning of the 20th century, first mapping surveys of vegetation in threatened species appeared [@quilter_low_2000], while during the first decade the number of publications began to increase significantly [@hardin_small-scale_2013].  At present there are some initiatives that seek to determine the current state of the RPAS in ecology and conservation. Recently, the journals  *Remote Sensing in Ecology and Conservation* and the *International Journal of Remote Sensing* made a call to the scientific community for the sending of proposals in order to update the current state of RPAS applied into the environmental spere. As result, a significant production of RPAS related papers on the matter is expected. On the other hand, it is remarkable the greater presence of web portals that center their activity around civil applications with RPAS. In the field of research applied to conservation, the website <http://conservationdrones.org/>  is a worldwide reference, whose contents illustrate recent pioneering projects, so they are not always reflected in the scientific literature. The popularity of RPAS has transcended the scientific-technical field, giving rise to the emergence of user communities with a large presence on the Internet. One of the most active portals is <http://diydrones.com/>, which brings together fans of the do-it-yourself philosophy that encourages the use of open platforms versus the traditional closed systems offered by the traditional industry. This has unchained the reduction of costs of these equipment and, together with the development of specialized open source software, have led to the democratization of technology, bringing it closer to a broad number of users and organizations. The scientific community has probably benefited from this general trend. For some authors, the flexibility in the assembly of RPAS offers in principle a greater degree of customization, allowing to combine different sensors and control systems, according to the particular needs of each project and without having to depend on others  beyond the research group itself [@koh_dawn_2012]. In the commercial field, more companies offer RPAS of high performance and reliability along with professional services and software, so the sector benefits from  great dynamism.

## Protected areas 

As defined by UICN, "a protected area is a clearly defined geographical space, recognized, dedicated and managed, through legal or other effective means, to achieve the long term conservation of nature with associated ecosystem services and cultural values" [@dudley_guidelines_2008]. Despite the fact that the number of protected areas has raised  considerably at a global level, with 15.4% of the land area and 8.4% of the marine areas under some protection figure  [@juffe-bignoli_protected_2014] the size of wildlife populations has been estimated to have decreased by 52% in the period 1970 to 2012. Habitat change and fragmentation, severe pollution particularly in freshwater ecosystems, overexploitation of resources, climate change and the impact of invasive species on indigenous populations have been identified as the main threats to biodiversity [@barnosky_has_2011; @secretariat_of_the_convention_on_biological_diversity_global_2006]. To address the current environmental crisis, the Convention on Biological Diversity (CBD) established in Nagoya, Japan, a strategic plan for the period 2011-2020 which includes the so-called Aichi targets for biological diversity. Among the stated objectives is the increase of protected area systems of particular importance for biodiversity and ecosystem services (target 11).

Protected areas are reference sites for monitoring and managing biodiversity. As part of the large array of observing systems monitoring ecosystems and measuring human impacts  [@forum_toward_2008, @pereira_essential_2013], RPAS can fill the gap at an intermediate spatial scale, surpassing the financial and technological  constrains of remote sensing and ground / aerial manned vehicles based surveys  [@koh_dawn_2012; @rodriguez_eye_2012; @chabot_wildlife_2015]. First, while it is possible to acquire satellite images at low or virtually zero cost (LandSat, MODIS, Sentinel, etc.), most of these platforms operate on a global or regional scale. The limited spatial and temporal resolution, along with the inconveniences of cloud presence especially noticeable in tropical areas, reduces the effectiveness of remote sensing in the collection of data at fine-scale, according to the requirements of ecological studies at the level of species, habitats or populations  [@wulder_high_2004]. Secondly, the large extent of these protected areas significantly increases the costs of field work on foot, particularly in hadarzous and inaccessible areas. Finally, while manned aerial vehicles offers an optimal alternative for covering much larger areas, they suffer from excessively high operational costs and when not used for aerial mapping, it could be affected by observer bias. In addition, air accidents are ranking as the leading cause of death in wildlife specialists in the United States [@sasse_job-related_2003]. As a consequence, RPAS have been positioned as an appropriate complement for conservation activities  [@zahawi_using_2015] avoiding to a certain extent some of the above-mentioned drawbacks. In developing countries, especially sensitive in terms of budgetary allocations and technical capacities, monitoring and surveillance programs are being successfully developed through the use of RPAS. For instance, by capturing aerial images in the Volta delta, Ghana, a team of scientists measured the effects of climate change on coastal areas and evaluates the effectiveness of prevention and restoration measures against erosive processes [@Georg2016].

## Legal barriers
 
RPAS operations faces important legal barriers that undermine the true potential in the civilian sphere  [@stocker_review_2017]. An overly restrictive regulatory framework could limit the possibilities of use of the RPAS in the field of conservation, which makes clear the urgent need to harmonize legislation . In the United States and in most of the European countries consulted, interim legislation has been adopted which, to a certain extent, equates the management of RPAS with that of traditional aircraft. In general terms, the situation in Latin America is uneven, however there is a general tendency to develop specific laws to cope with the rise of the RPAS in both the civil and military sectors [@Bworld_of_drones2017]. Africa is one of the continents where the impact of RPAS in conservation has had greater repercussions. However, in the opinion of some conservationists, their use has not been without problems, resulting in governments that have totally or partially prohibited drone operations, arguing national security problems in detriment of protection of natural areas  [@Andrews2014]. But RPAS have also been generally welcomed in several developing countries in Asia, where an array of related programs are being carried out [@nugraha_urgency_2016]. The uncertainty of the users along the world has promoted the development of associations in order to advise on the legal aspects to be taken into account during the operation, with the International Association for Unmanned Vehicle Systems (AUVSI) <http://www.auvsi.org>  being the largest nonprofit organization in the world dedicated to advancing the community of  unmanned aerial vehicles users.

# Methods

To achieve the proposed objectives, a bibliographical review of scientific articles, gray literature, postgraduate theses, websites and specialized journals was carried out, following a similar line to other studies [@linchant_are_2015; @christie_unmanned_2016]. The main tools for selection of the cited bibliography include Google Schoolar, Research Gate and Mendeley Desktop, while the use of Internet search engines include other references outside the scientific scope. Key search criteria for keywords included unmanned aerial vehicles in their various meanings and acronyms (RPAS, UAV, drones, etc.), along with a variety of terms referring to natural protected areas, primarily in English. Last references revised were published on June, 2017.

The selected information was categorized according to the role played by RPAS in direct or indirect relation to conservation in protected areas. It is presented in tabular format, identifying where the study was conducted, the expected accomplishments and technical specifications of the aerial platform. After posing main results obtained, gaps are indentified and possible scenarios for implementing  RPAS as essential tools to help achieve conservation plans in protected areas are discussed, highlighting some trends and opportunities that apparently have not yet been adequately exploited.

# Results

## Wildlife Monitoring and Management

Manned aircraft have been traditional used to undertake a variety of ecological surveys. As remarked by most papers reviewed  such techniques are risky, costly and despite several efforts to minimize error estimation [@cook_design_1979] are subject to visibility bias since a greater number of observers is required to guarantee an exhaustive count of populations. RPAS have emerged as a feasible alternative to surpass such inconveniences. Several studies addressed counting large terrestrial mammals with positive contributions [@jain_unmanned_2013, @lancia_estimating_2005, @mulero-pazmany_unmanned_2015]. [@colefax_potential_2017] reviewed the potential of RPAS to survey species relying on coastal and marine ecosystems. RPAS have as well been applied to study population dynamics in bird colonies  [@sarda-palomera_fine-scale_2012], but also in the inspection and characterization of inaccessible nesting sites using multi-rotors [@weissensteiner_low-budget_2015]. In some cases, in order to overcome the barriers to directly detect the species of interest, the studies focused on locating and characterizing their breeding and nesting areas [@van_andel_locating_2015, @szantoi_mapping_2017, @andrew_semi-automated_2017, @wich_preliminary_2016]. 

On the other hand, one of the central themes in ecology is the development of surveys and statistical models for estimating  abundance and distribution of animals in wild populations [@lancia_estimating_2005; @mateo_modelos_2011]. Such methods allow inferring the potential or suitable habitat of organisms by collecting environmental information and species presence data from different sources and techniques.  Wildlife telemetry tracking is one of the most common methods used to gather movement data. [@mulero-pazmany_unmanned_2015] compared the performance of RPAS as tools for data collection against biologgers when estimating spatial distribution of foraging domestic herbivores impacting food availability in natural areas, easily identifiable by high-resolution aerial images obtained by photographic sensors on board. Targeting cattle (*Bos taurus*), the authors obtained similar results regarding the performance of the models, but they emphasized the cost-benefit factor of RPAS as the main advantage. In general, the relatively expensive purchase of electronic tracking devices limits their availability for research purposes, reducing sample size. Added to the risk of marking individuals under non-random criteria, it is argued that  robustness of the analysis can be seriously affected. However, main advantage of wildlife telemetry is its ability to provide a large amount of data for longer periods of time. Nevertheless, the authors pointed out that both methodologies have the potential to complement each other throughout all phases of the study. Other innovative techniques have recently been illustrated in scientific papers evaluating the feasibility of pairing radio locators in RPAS in the search for individuals marked with VHF radio collars [@soriano_rf-based_2009, @korner_autonomous_2010; @bayram_active_2016; @cliff_online_2015; @leonardo_miniature_2013].  

Given the large amount of information generated, it is not surprising that software have been developed in the field of computer vision and machine learning  to handle the automatic detection, recognition and counting of individuals captured in scenes acquired by visible and thermal-infrared sensors, replacing otherwise time-consuming manual tasks  [@lhoest_how_2015; @abd-elrahman_development_2005; @van_gemert_nature_2015, @chabot_computer-automated_2016, @christiansen_automated_2014]. 

Outside the scientific literature, there are projects for monitoring wildlife in both marine and terrestrial ecosystems, generally supported by non-governmental organizations and research centers. Based on information gathered at <https://conservationdrones.org> several studies have been identified pursuing methods for registering  individuals in marine mammal populations, primates and macrofauna in general. For instance, a work conducted in the Amazon Basin in Brazil is testing the use of RPAS to improve the density and abundance estimation of different species of dolphins, compared with direct observation by specialists [@WichS2017]. The main research aims include the validation and harmonization of both methodologies and, indirectly, evaluate the feasibility for its regular application in monitoring projects with a similar purpose, taking into account the cost-benefit of the execution.

\include{tables}

## Infrastructure and risk assessment
  
Other research projects highlight the convenience of RPAS in assessing the risk  that human infrastructure posed for wildlife, which results in the implementation of more cost-effective preventive measures. For instance, some species of birds nest on high voltage power lines poles, making them especially vulnerable to death by electrocution. [@margarita_mulero-pazmany_juan_jose_negro_low_2014] used a long endurance fixed-wing RPAS as a low cost alternative for visual evaluation of linear electrical structures.  Collisions with the wiring is one of the most common causes of death in birds. [@lobermeier_mitigating_2015] proposed to install marks that are easily visible through the use of robotics arms installed in multicopters. Due to the ease of maneuvering of the platform, multicopters are more suitable for precision work. As a pre-harvest activity, generally performed under mechanical procedures, [@mulero-pazmany_margarita_aeromab_2011] suggested a flyby to identify possible nests on the ground, and if necessary, take appropriate actions to avoid their destruction. 

## Monitoring and mapping of terrestrial and aquatic ecosystems

The maturity of remote sensors on board air or space platforms has led to an increase in applications for the study of ecosystems [@wulder_high_2004]. The data obtained have enabled the development of vegetation and soil maps, enhance the characterization of habitats or the understanding of the structure and function of forest ecosystems, develop digital elevation models or geomorphological maps. The emergence of RPAS permits the quantitative analysis of habitats to a level of detail ever reached, either for economic reasons or for technological limitations. This momentum has been especially notable with the parallel development of affordable multispectral and hyperspectral sensors adapted to small aircraft [@bareth_low-weight_2015]. RPAS has been used by The United States Geological Survey (USGS)  to classify vegetation cover in wetlands  [@USGS2014]. [@zaman_use_2011] monitored the spread of invasive species in such ecosystems while [@mullerova_does_2016] assessed the  importance of spectral and spatial resolution to detect plant invasion  using satellite, aerial and  RPAS data. [@perroy_assessing_2017] conducted several flight to quantify the detection rate of invasive species under different flight parameters, enviromental conditions and vegetation cover. The characterization of forest stands constitutes an important section, considering the number of papers facing the issue from different perspectives. [@gini_aerial_2012] employed a quadcopter model operated at low-height and RGB and NIR cameras in small areas. Due to the reduced reliability and autonomy of the platform and the difficulties to increase the load capacity, the flight planning is reduced to three passes with a percentage of 80% and 30% of longitudinal and transverse overlap respectively. [@lisein_discrimination_2015]  performs a multitemporal analysis of the spectral response to phenological variations in different species of deciduous trees and concluded that  intraspecific spectral variation is of maximum interest for the optimization of classification algorithms and discrimination between species. During the research, the authors operated a fixed wing RPAS model, used different sensors in the visible and near infrared range and optimized the flight parameters to cover the maximum surface area with the fewest possible number of flights. [@zahawi_using_2015] applies the Ecosynth methodology, a toolkit for mapping and measuring 3D vegetation using digital cameras and artificial vision open source software.  Such project was aimed to evaluate the effectiveness of restoration actions in forests using RPAS as a viable alternative for traditional field measurements and applying different  predictive models of frugivorous birds presence by means of height and canopy structure data. Recently, shallow coastal habitats were also mapped using  consumer grade RPAS [@casella_mapping_2017, @ventura_low-cost_2016], including monitoring erosion dynamics in shorelines. [@casella_drones_2016].

## Surveillance and support for compliance with laws in protected areas

RPAS have also  relevance in the control and surveillance of protected areas, documented through different experiences focused mainly on controlling poaching. Due to the nature of these activities, emphasis has been placed on improving first-person vision (FPV) methods to obtain a clear, real-time view of the monitored area. Also, it is prefereable the use of fixed-wing RPAS for longer flight times and consequently cover greater areas. Other requisites include the convenience of using thermal cameras in low visibility conditions, generally related to hours of greater furtive activity, along with advances in computer vision systems programmed to detect the presence of humans and target species under pressure from illegal trade in protected areas. [@mulero-pazmany_remotely_2014] focused on the African rhinoceros (*Diceros bicornis*, *Ceratotherium simum*) and noted the advantages of  real time video compared to still photography, which despite the better overall quality, requires  longer post-processing time. In addition, authors emphasized the need to improve the resolution of thermal sensors to increase the chances of detecting suspicious activity at night time.  [@franco_five_2016] suggested using RPAS to combat poaching and illegal fishing activities in marine protected areas (MPA), claiming million-dollar economic losses in the fishing sector.  [@duffy_waging_2014] analyzed the consequences of the militarization of conservation practices as an increasing trend in natural protected areas around the world and illustrates the use of RPAS through several examples.

## Ecotourism

The high degree of diversification offered by  RPAS in the ecotourism industry is summarized in a recent article, which shows possible recreational activities, business opportunities, search and rescue operations, mapping and formulas for granting RPAS flight permits  in designated areas  [@king_will_2014]. Within the still scarce literature,  [@hansen_applying_2016] values the effectiveness of RPAS in monitoring visitors in marine and coastal areas, in combination with other innovative solutions. According to the author the RPAS would theoretically allow to operate under different environmental conditions, improving the level of detail and offering a continuous coverage in the flow and behavior of  visitors, as opposed to other techniques of habitual use like the manual observation or the installation of networks of surveillance cameras. 

## Impact of RPAS on wildlife and ecosystems

Animal welfare in wildlife management  practices and ecological research is a sensitive issue from which ethical issues arise [@wilson_measuring_2006]. Not surprisingly, RPAS are not exempt of discussion.  [@vas_approaching_2015] assessed the impact of color, speed and angle of flight on the behavioral responses of wetland birds. The  latter factor was considered  the primary trigger for changes in behavioral patterns, especially in vertical approaches at an angle of 90º. Finally, a core set of recommendations is included,  and authors encouraged to extend the trials to a wide range of RPAS and species. [@mcevoy_evaluation_2016] accomplished the most intensive disturbance assesment on waterfowl to date, by combining an array of fixed-wing and rotor-wings RPAS at various altitudes. [@scobie_wildlife_2016] quantified noise detection by several representative species, suggesting flying higher than 200 meters to minimise noise disturbance. [@ditmer_bears_2015] measured physiological stress in American black bear (*Ursus americanus*) by electronic recording of cardiac activity in the presence of RPAS. Although no changes in behavior patterns are detected, heart rate (measure in beats per minute) was significant higher in most cases observed. [@pomeroy_assessing_2015] noticed evidence of variation in reactivity in seal populations based on a variety of factors, from the RPAS platform, flight height and lateral distance to the breeding or moulting season. No adverse reactions were reported in elephants (*Loxodonta africana*) or cattle (*Bos taurus*) on flights at a minimum height of 100 meters [@jain_unmanned_2013, @mulero-pazmany_unmanned_2015]. [@weissensteiner_low-budget_2015] observed similar disturbance patterns using RPAS with respect to manual inspection when documenting nesting status in hooded crows, but they emphasized the shorter period of stress to which birds are exposed, along with reducing or eliminating risk in climbers and avoiding damages to trees. In the absence of further experiences to date explicitly addressing animal welfare, [@hodgson_best_2016] suggested  a series of general recommendations as the basis for a code of good practice, highlighting the adoption of the precautionary principle and respect for aviation standards, the specific training of operators, the appropriate selection of equipment, the cessation of operations in the case of obvious disturbances in the populations studied and the reporting of observations in scientific publications, that allows sharing of knowledge to progressively improve the protocols of operations with RPAS that involve the observation of fauna. [@mulero-pazmany_unmanned_2017]  carried out an up-to-date systematic review of literature documenting RPAS disturbance effects in wildlife and outlined some findings, while complementing the previously mentioned recommendations. The authors agreed that noise level and intensity  are the main, but not the only factor inducing animal reactions in presence of RPAS, where birds are the most sensitive species, followed by terrestrial mammals and aquatic animals. These response patterns are also influenced by life-history stage and level of aggregation of targeted species.

# Environmental management and decision support

Planning in protected areas is reflected through a variety of management programs that are difficult to fit into some of the previously discussed categories. An extensive report based on Christmas Island proposed dropping poisoned baits from RPAS to eradicate feral cats disturbing threatened native species [@mccaldin_use_2015]. [@cornell_use_2016]  obtained ground truth data by adapting  RPAS to take water samples for comparison with hyperspectral measurements of Landsat 8 Operational Land Imager (OLI).  [@zang_investigating_2012] identified several pollution agents in riparian areas using RPAS imagery. [@fornace_mapping_2014] considered mapping enviromental risk factors for predicting zoonotic diseases as part of a extensive epidemiological study carried out in Philippines and so on. Literature citing RPAS for search and rescue activities  is profuse and an in-depth revision is beyond the scope of this article, but a recent publication ilustrate several examples where RPAS were succesfully operated to assist rescue teams [@van_tilburg_first_2017]. A google scholar search sorted by relevance using disaster management and drones keywords throws at first place a complete report describing a complex framework for decision support using RPAS [@maza_experimental_2011]. RPAS in the fight against wildfires has transcended the scientific field and is currently on the agenda of many goberments and 


# Discussion 

Most of the sources analyzed focus on local-scale conservation projects and feasibility studies of RPAS monitoring distribution and abundance of wildlife populations. Literature begins to be equally prolific in mapping activities in terrestrial and aquatic ecosystems, a niche until recently entirely occupied by aerial and space platforms for environmental remote sensing. Despite the low number of scientific articles addressing the use of RPAS in the control and surveillance of natural protected areas, it is still one of the issues that more social debate generates and it is not strange to find governmental initiatives or promoted by environmental organizations in the fight against poaching. From the economic point of view,  expenses derived from the operation with RPAS are hardly quantifiable. Not all studies consider the effort required for the development of technical and analytical skills of work teams. Computational requirements are demanding and certain phases of information processing requires the acquisition of software whose price is generally high. Also, operations with RPAS are not exempt from accidents, which has an negative impact on the budget originally planned. In addition, statistical and sampling methods approaching the analysis of data are mostly in its infancy and further research should be accompased to assess the overall performance of these methods.

## Wildlife Monitoring and Management

Both fixed-wing and rotor-wing RPAS might become very handy tools for conservation practitioners. Wildlife census campaigns, usually carried out by going in on foot, terrestrial vehicles or by vessel deployment in aquatic environments, could be supplemented or replaced by RPAS mapping and monitoring capabilities. As becoming easier to operate, there are sufficient grounds to encourage park rangers training in the use of RPAS, which are subject in many cases to time-consuming and often dangerous raids. If operated responsibly, it could be closer of being considered a non-invasive and reliable monitoring technique [@jewell_effect_2013-1]. From the technological point of view, "Follow-me"" capabilities of RPAS constitute a promising advance in animal movement and remote sensing disciplines, by having high-resolution aerial imagery from places frequently visited or crossed by electronically tagged species.     

## Infrastructure and risk assessment

Wildlife risk assessment could benefit from RPAS by promoting their use for preventive purposes in conflicting areas where human factor is indirectly causing the killing of many species.  Relative low operational cost of RPAS make them an attractive alternative to manual inspection, which may foster such practices. Since the literature citing RPAS for such purposes is limited, we propose that they could serve to reduce fatalities by scheduling periodic flights monitoring facilities, roads crossing sensitive areas and coastal ecosystems where vessels strikes with aquatic species is frequent. RPAS might also help to persuade birds from approaching power lines, wind turbines and other potential hazards, just as it has been applied to keep airports safe.

## Monitoring and mapping of terrestrial and aquatic ecosystems

The integration of classical remote sensing elements developed during the last decades in the scope of RPAS opens new possibilities in the observation of environmental phenomena at local scale, complementing other systems of Earth observation. Protected area managers should be aware of the benefits of having information on demand. As requirements change, Information Technology (IT) departments in protected areas must be ready to integrate data into effective conservation strategies and better decision-making. The inclusion of RPAS in monitoring activities should be weighed against the increasing complexity of such systems.

## Surveillance and support for compliance with laws in natural protected areas

The convenience of using RPAS in the fight against poaching and illegal fishing in protected areas faces important technical and legal constraints. First, the reviewed literature mention the need to design more efficient live vision systems. Low autonomy of  RPAS is especially critical in large natural parks, limiting the area under surveillance. Issues concerning atmospheric conditions have not yet been completely resolved. [@banzi_sensor_2014] proposed a sensor based economical feasible anti-poaching alternative, arguing that RPAS fulfilling suitable specifications are costly, especially in developing countries. However, as technology becomes more accesible, it is expected that main barriers will appear in the legislative and social sphere. In some countries it is forbidden to fly beyond the visual range of the operator, limiting the effectiveness of the inspection in real time. RPAS applied to surveillance of protected areas is also questioned arguing human right breaching [@banzi_sensor_2014]. Some detractors are skeptical about the ability of RPAS to persuade offenders, who in many cases face situations of greatest need. Probably the success of such initiatives requires a greater consensus among the parties involved and the development of strategies that seek to solve the causes of poaching. Surveillance  of illegal logging activities  or bonfires detection in unauthorized areas have great potential and may be convenient to implement.

## Ecotourism

A permissive regularization of  RPAS in ecotourism activities in natural parks could lead to unpredictable situations. On the one hand, the constant presence of sources of noise coming from propellers and engines, the sensation of invasion or lack of privacy, security issues and the visual impact of RPAS on the landscape could negatively affect the tourist experience. It is well known that the consequences triggered by RPAS disturbing wildlife have led to the ban on flying them in national parks in the United States and other protected areas of the world. As result of potential enviromental impact due to the use of RPAS by tourist in Antarctica, [@leary_drones_2017] reported the partial prohibition of recreational RPAS in coastal areas as part of a more extensive regulation promoted by stakeholders. Such regulation looks reasonable and could be the way forward for other protected areas to adapt the allowed activities with RPAS. It seems obvious to deduce that in the hands of non-skilled operators, the risk of accidents and losses would increase. This may lead to the aforementioned widlife disturbance, but they also pose a risk for contamination of water supplies or the triggering of fires in sensitive areas due to the presence of flammable and toxic components, fueling the low popularity of RPAS to the detriment of the benefits they bring. It does not appear that feasibility studies or opinion polls have been published that respond to the issues raised and to the ethical and legal implications derived from their use. Even when the leisure possibilities are wide and recognized, it would be advisable to be cautious in the face of the demand of the ecotourism industry to incorporate  RPAS in their activities. 

## Impact of RPAS on wildlife and ecosystems

The review of the literature suggests that there are still certain niches that need more attention from the research community. The ethical implications of RPAS in wildlife studies have not yet been adequately weighed since most studies only marginally address the presence or absence of reactions in species in the vicinity of RPAS. Despite the greater degree of awareness reflected in a emergent set of guidelines [@hodgson_best_2016; @mulero-pazmany_unmanned_2017] , we consider that further trials aimed at quantifying physiological and behavioral changes targeting a broader group of wild species should be carried out.  The establishment of a best practices and recommendations manual could increase the chances of integrating the responsible use of RPAS in conservation and management activities in natural areas.  Moreover, some authors mentioned the lack of commercial operators with sufficient expertise to carry out such activities [@mcevoy_evaluation_2016].  Also, an optimal trade-off between  benefits and environmental costs should be pursued [@gremillet_robots_2012; @sepulveda_review_2010]. By designing quieter, non-polluting and safer components, the impact on wildlife and ecosystems could be reduced and its objective observation facilitated. Nonetheless we trust that, as far as further testing be done, RPAS has great potential to replace more invasive monitoring techniques, whose reliability is challenged by the potential to induce conditions of unacceptable stress in wildlife that could ultimately invalidate the results of the research [@jewell_effect_2013, @wilson_measuring_2006]. This should be consciously taken into account by the many actors involved  in protected areas activities when they are reluctant to allow RPAS to be an essential part of research and conservation activities.
  
# Environmental monitoring and decision support
  
Protected areas are subject to periodic environmental quality control procedures where RPAS could play a major role.  Also, RPAS are suitable to assist decision making where rapid response is crucial by offering valuable information at real time to handle natural and man-made disasters. Forest fires is a major concern in natural parks and is not rare that RPAS have been put foward to assist in prevention, fighting and evaluation phases. In most cases, such applications have operational requirements which eventually are costly. For instance,  sofisticated on-board instruments, gas powered engines for longer endurance and higher payloads or robotics arms and containers designed to assist sampling, hold cargo or deliver assistance. RPAS could leverage wildlife capture procedures by carrying dart guns for chemical immobilization where otherwise manual approaching free-ranging animals is considered inefficient or dangerous.


# Conclusions 

The consolidation of the RPAS as management and research tools in protected areas is closely linked to the technological development of the elements associated with the platform and to the establishment of measures that favorably regulate its use, increasing opportunities in the sector and stimulating innovation in priority conservation areas. There are continually improvements in navigation control and flight autonomy, while we are witnessing the progressive miniaturization and diversification of sensors along with advances in the field of artificial intelligence. This rapidly expanding confluence of factors encourages the emergence of new scenarios with ethical and legal implications. Most governments have reacted by setting constraints that could have a negative impact on the capacity to integrate RPAS into the civilian sphere, despite some progress in this regard. As a result, it is difficult to foresee the actions that each country will adopt from now on in an attempt to harmonize the contradictions presented by RPAS, reason why it is probable that the future of the RPAS in protected areas is conditioned fundamentally by political and social factors.

# References 
